# Development environment configuration
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/internproject
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

api:
  openai:
    key: ${OPENAI_API_KEY}
    url: ${OPENAI_API_URL}

jwt:
  secret: ${JWT_SECRET}

app:
  cors:
    allowed-origins: "http://localhost:3000"
    allowed-methods: "GET,POST,PUT,DELETE,PATCH,OPTIONS"
    allowed-headers: "*"
